# Pandas : Foundations

**What you'll learn:**
1. What pandas is and why it exists
2. Installation and import conventions
3. The two core data structures: Series and DataFrame
4. Creating Series and DataFrames from scratch
5. Reading data from CSV files
6. Basic inspection: head, tail, info, describe, shape
7. Index, columns, and dtypes

### Where pandas fits

NumPy gives you fast math on arrays of numbers, but real-world data is messier than that: column names, mixed types, missing values, dates, categories. pandas adds the structure and tools you need to work with that kind of data, while still leaning on NumPy underneath for performance.

Almost every data-related role uses pandas day to day, so it's worth getting comfortable with.

## What is pandas?

### definition

> "pandas is a fast, powerful, flexible and easy to use open source data analysis and manipulation tool, built on top of the Python programming language." - pandas.pydata.org

In simpler words: pandas is a Python library for **labeled, tabular data**. Think of it as Excel-style tables, but programmable.

### What pandas adds on top of NumPy

| Feature | NumPy | pandas |
|---|---|---|
| Fast array math | Yes | Yes (uses NumPy underneath) |
| Mixed types (numbers + strings + dates) | No | Yes |
| Labeled rows and columns | No | Yes |
| Read CSV / Excel / SQL / JSON | Limited | Yes |
| Missing value handling | Manual | Built-in |
| Group by / pivot operations | No | Yes |
| Time series support | Basic | Full |

### Where it gets used

- Data cleaning and transformation (preparing data for ML)
- Exploratory Data Analysis (EDA)
- Financial and time series analysis
- Loading and reshaping datasets
- Joining and merging tables (similar to SQL)
- Reporting and dashboards


- **Tabular data**: data arranged in rows and columns, like a spreadsheet or a database table.
- **EDA (Exploratory Data Analysis)**: the initial pass of looking at a dataset to understand its shape, distributions, missing values, and obvious patterns. The term was coined by statistician John Tukey in 1977.
- **SQL (Structured Query Language)**: the standard language for querying relational databases. Many pandas operations have a direct SQL equivalent.

### History

pandas was created in 2008 by Wes McKinney while he was working at AQR Capital, a hedge fund. He needed a Python tool with the data manipulation power of R. It's now downloaded over 200 million times a month and is the standard for tabular data in Python.

## Installing and Importing pandas

### Installation

If you're using Anaconda or Google Colab, pandas is already installed. Otherwise:

```bash
pip install pandas
```

### The standard import

```python
import pandas as pd
```

The `pd` alias is as standard as `np` is for NumPy. Sticking with `pd` keeps your code consistent with what you'll see in tutorials, books, and Stack Overflow answers.

In [ ]:
Q   import pandas as pd
import numpy as np

print("pandas version:", pd.__version__)
print("NumPy version: ", np.__version__)

pandas version: 2.2.2
NumPy version:  1.26.4

## Series 
### definition

> "Series is a one-dimensional labeled array capable of holding any data type (integers, strings, floating point numbers, Python objects, etc.). The axis labels are collectively referred to as the index." - pandas docs

In practice, a Series is like a single column from a spreadsheet: a list of values paired with labels (the index).

In [2]:
# Create a Series from a list
s = pd.Series([10, 20, 30, 40, 50])
print(s)
print(f"\nType: {type(s).__name__}")

0    10
1    20
2    30
3    40
4    50
dtype: int64

Type: Series

Notice the two columns in the output:
- The left column (0, 1, 2, ...) is the **index** (the labels).
- The right column is the values.
- **dtype** is the data type of the values, same idea as in NumPy.

A quick note on **Index**:

> "Index is the basic object storing axis labels for all pandas objects." - pandas docs

The Index holds the labels for an axis (rows for a Series, rows or columns for a DataFrame) and supports lookups, slicing, and alignment between objects.

### Custom index labels

In [3]:
# Use meaningful labels instead of integers
temperatures = pd.Series(
    [22, 28, 19, 35, 18],
    index=['Mon', 'Tue', 'Wed', 'Thu', 'Fri']
)
print(temperatures)

Mon    22
Tue    28
Wed    19
Thu    35
Fri    18
dtype: int64

In [4]:
# Access by label or position
print("Tuesday's temp:", temperatures['Tue'])
print("Day at position 0:", temperatures.iloc[0])

# Multiple labels at once
print("\nMonday and Wednesday:")
print(temperatures[['Mon', 'Wed']])

Tuesday's temp: 28
Day at position 0: 22

Monday and Wednesday:
Mon    22
Wed    19
dtype: int64

### Series supports NumPy operations

Because a Series is backed by a NumPy array, arithmetic, comparisons, and aggregations work the same way.

In [5]:
# Math works just like NumPy
print("Original:")
print(temperatures)

print("\nConverted to Fahrenheit:")
print(temperatures * 9/5 + 32)

print("\nDays above 25C:")
print(temperatures[temperatures > 25])

print(f"\nMean: {temperatures.mean()}")
print(f"Max:  {temperatures.max()}")
print(f"Min:  {temperatures.min()}")

Original:
Mon    22
Tue    28
Wed    19
Thu    35
Fri    18
dtype: int64

Converted to Fahrenheit:
Mon    71.6
Tue    82.4
Wed    66.2
Thu    95.0
Fri    64.4
dtype: float64

Days above 25C:
Tue    28
Thu    35
dtype: int64

Mean: 24.4
Max:  35
Min:  18

### Series from a dict

When you build a Series from a dictionary, the dict keys become the index and the dict values become the data.

In [6]:
capitals = pd.Series({
    'Pakistan': 'Islamabad',
    'India':    'New Delhi',
    'China':    'Beijing',
    'Japan':    'Tokyo',
    'USA':      'Washington D.C.'
})
print(capitals)

Pakistan          Islamabad
India             New Delhi
China               Beijing
Japan                 Tokyo
USA         Washington D.C.
dtype: object

## DataFrame - The Main Event

### definition

> "DataFrame is a 2-dimensional labeled data structure with columns of potentially different types. You can think of it like a spreadsheet or SQL table, or a dict of Series objects." - pandas docs

A few ways to picture a DataFrame:
- A dict of Series, where each column is a Series
- A spreadsheet
- A SQL table
- A 2D NumPy array with row labels and column names

### Creating a DataFrame from a dict

In [12]:
# Each key is a column name, each value is the column's data
data = {
    'name':    ['Ayesha', 'Sara', 'Ahmed', 'Fatima', 'Hassan'],
    'age':     [26, 25, 19, 28, 21],
    'city':    ['Lahore', 'Karachi', 'Islamabad', 'Lahore', 'Karachi'],
    'score':   [86, 92, 78, 88, 71]
}

df = pd.DataFrame(data)
print(df)

     name  age       city  score
0  Ayesha   26     Lahore     86
1    Sara   25    Karachi     92
2   Ahmed   19  Islamabad     78
3  Fatima   28     Lahore     88
4  Hassan   21    Karachi     71

That's a real DataFrame. The leftmost column (0, 1, 2, 3, 4) is the index. The top row (name, age, city, score) holds the column labels.

### Creating from a list of dicts (records format)

This layout is often called the **records format**: a list where each entry is a dict representing one row.

In [8]:
records = [
    {'name': 'Ali',    'age': 22, 'score': 85},
    {'name': 'Sara',   'age': 25, 'score': 92},
    {'name': 'Ahmed',  'age': 19, 'score': 78},
]

df2 = pd.DataFrame(records)
print(df2)

    name  age  score
0    Ali   22     85
1   Sara   25     92
2  Ahmed   19     78

### Creating from a NumPy array

When the data is already in a NumPy array, you just pass it in and provide column names (and optionally an index).

In [9]:
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

df3 = pd.DataFrame(arr, columns=['A', 'B', 'C'])
print(df3)

   A  B  C
0  1  2  3
1  4  5  6
2  7  8  9

### Setting a custom index

By default the index is a range of integers (0, 1, 2, ...). You can replace it with anything more meaningful: names, IDs, dates, and so on.

In [10]:
data = {
    'age':   [22, 25, 19, 28],
    'score': [85, 92, 78, 88]
}

df4 = pd.DataFrame(data, index=['Ali', 'Sara', 'Ahmed', 'Fatima'])
print(df4)

        age  score
Ali      22     85
Sara     25     92
Ahmed    19     78
Fatima   28     88

## Reading Data from Files

In practice, most of the time you load data from a file rather than typing it in by hand. Let's create a CSV and load it.

A quick definition before we go further:
- **CSV (Comma-Separated Values)**: a plain text format for tabular data. Each line is a row, and columns are separated by commas (or sometimes by other delimiters such as tabs or semicolons).

In [ ]:
# Create a sample CSV file for the examples
sample_csv = '''student_id,name,age,city,gpa
1,Ali,22,Lahore,3.5
2,Sara,25,Karachi,3.8
3,Ahmed,19,Islamabad,2.9
4,Fatima,28,Lahore,3.6
5,Hassan,21,Karachi,3.1
6,Ayesha,23,Peshawar,3.7
7,Bilal,20,Lahore,2.8
8,Maryam,24,Karachi,3.9
9,Usman,22,Islamabad,3.4
10,Zara,26,Lahore,3.2
'''

with open('students.csv', 'w') as f:
    f.write(sample_csv)

print("Sample CSV created at students.csv")

Sample CSV created at /tmp/students.csv

In [15]:
# Read the CSV — this is the most common pandas operation in the world
df = pd.read_csv('students.csv')

# Show the first 5 rows
print(df.head())

   student_id    name  age       city  gpa
0           1     Ali   22     Lahore  3.5
1           2    Sara   25    Karachi  3.8
2           3   Ahmed   19  Islamabad  2.9
3           4  Fatima   28     Lahore  3.6
4           5  Hassan   21    Karachi  3.1

One line, and you have a working DataFrame. pandas infers the column names from the header row and the data type of each column from the values.

### Other read functions

| Function | File type |
|---|---|
| `pd.read_csv()` | Comma-separated values |
| `pd.read_excel()` | Excel `.xlsx` files |
| `pd.read_json()` | JSON files |
| `pd.read_sql()` | SQL database query |
| `pd.read_html()` | HTML tables from a webpage |
| `pd.read_parquet()` | Parquet (a fast binary format) |

Definitions for the formats above:
- **JSON (JavaScript Object Notation)**: a text format for structured data, commonly used in APIs.
- **HTML (HyperText Markup Language)**: the standard markup language used for web pages. `read_html` looks for `<table>` elements in a page.
- **Parquet**: a columnar storage format designed for efficient reading and compression, common in big-data workflows.

`read_csv` is the one you'll use most. Most of these functions share similar arguments, so once you learn one the others feel familiar.

### Common `read_csv` arguments worth knowing

In [16]:
# Common variations — try with different settings
# (These won't all work on our simple CSV, just showing the syntax)

# df = pd.read_csv('file.csv', sep=';')              # different delimiter
# df = pd.read_csv('file.csv', header=None)          # no header row
# df = pd.read_csv('file.csv', names=['a','b','c'])  # provide column names
# df = pd.read_csv('file.csv', index_col='id')       # use a column as index
# df = pd.read_csv('file.csv', nrows=100)            # read only 100 rows
# df = pd.read_csv('file.csv', usecols=['name','age'])  # only some columns
# df = pd.read_csv('file.csv', dtype={'age': 'int32'}) # specify dtypes

print("Above are common arguments — refer back when needed.")

Above are common arguments — refer back when needed.

## Inspecting Your Data

When you load a new dataset, the first thing to do is look at it. pandas has a small set of methods built specifically for that.

In [17]:
# head(): first N rows (default 5)
df.head()

   student_id    name  age       city  gpa
0           1     Ali   22     Lahore  3.5
1           2    Sara   25    Karachi  3.8
2           3   Ahmed   19  Islamabad  2.9
3           4  Fatima   28     Lahore  3.6
4           5  Hassan   21    Karachi  3.1

In [18]:
# tail(): last N rows
df.tail(3)

   student_id    name  age       city  gpa
7           8  Maryam   24    Karachi  3.9
8           9   Usman   22  Islamabad  3.4
9          10    Zara   26     Lahore  3.2

In [19]:
# shape: (rows, columns)
print(f"Shape: {df.shape}")
print(f"Rows: {df.shape[0]}, Columns: {df.shape[1]}")

Shape: (10, 5)
Rows: 10, Columns: 5

In [20]:
# columns: list of column names
print("Columns:", df.columns.tolist())

# index: the row labels
print("Index:  ", df.index.tolist())

# dtypes: data type of each column
print("\nDtypes:")
print(df.dtypes)

Columns: ['student_id', 'name', 'age', 'city', 'gpa']
Index:   [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

Dtypes:
student_id      int64
name           object
age             int64
city           object
gpa           float64
dtype: object

### `info()` - the overview method

In [21]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   student_id  10 non-null     int64
 1   name        10 non-null     object
 2   age         10 non-null     int64
 3   city        10 non-null     object
 4   gpa         10 non-null     float64
dtypes: float64(1), int64(2), object(2)
memory usage: 532.0+ bytes

`info()` gives a quick summary:
- The shape (rows and columns)
- The dtype of each column
- The number of non-null values per column (so you can spot missing data right away)
- Memory usage

A definition to keep in mind:
- **Null / Missing value**: a value that is absent. In pandas this is usually shown as `NaN` (Not a Number) for numeric columns or `None` for object columns.

### `describe()` - statistical summary

In [22]:
df.describe()

       student_id        age        gpa
count    10.00000  10.000000  10.000000
mean      5.50000  23.000000   3.390000
std       3.02765   2.788867   0.378447
min       1.00000  19.000000   2.800000
25%       3.25000  21.250000   3.125000
50%       5.50000  22.500000   3.450000
75%       7.75000  24.750000   3.675000
max      10.00000  28.000000   3.900000

`describe()` shows count, mean, standard deviation, minimum, the 25th/50th/75th percentiles, and the maximum for every numeric column.

A few definitions:
- **Mean**: the average value (sum of values divided by count).
- **Standard deviation (std)**: a measure of how spread out the values are around the mean. A larger std means more variability.
- **Percentile**: the value below which a given percentage of the data falls. The 25th, 50th, and 75th percentiles are also called the quartiles. The 50th percentile is the **median**.

For non-numeric columns, use `describe(include='object')`:

In [23]:
df.describe(include='object')

       name    city
count    10      10
unique   10       4
top     Ali  Lahore
freq      1       4

## Accessing Columns

There are two ways to grab a column.

In [24]:
# Bracket notation — always works
ages = df['age']
print(ages.head())
print(f"\nType: {type(ages).__name__}")
# A single column is a Series!

0    22
1    25
2    19
3    28
4    21
Name: age, dtype: int64

Type: Series

In [25]:
# Dot notation — shorter but has limits
gpas = df.gpa
print(gpas.head())

# Dot notation FAILS if:
#   - column name has spaces ("first name" → must use df['first name'])
#   - column name conflicts with a method (e.g., df.mean is the method, not a column)
# Recommendation: prefer bracket notation; use dot for quick exploration

0    3.5
1    3.8
2    2.9
3    3.6
4    3.1
Name: gpa, dtype: float64

In [26]:
# Multiple columns — pass a LIST inside the brackets
subset = df[['name', 'age', 'gpa']]
print(subset.head())
print(f"\nType: {type(subset).__name__}")
# Note the DOUBLE brackets — outer for indexing, inner for the list

     name  age  gpa
0     Ali   22  3.5
1    Sara   25  3.8
2   Ahmed   19  2.9
3  Fatima   28  3.6
4  Hassan   21  3.1

Type: DataFrame

The key idea: `df['col']` returns a Series. `df[['col1', 'col2']]` returns a DataFrame. The double brackets trip a lot of people up at first - the outer brackets are the indexing operation, and the inner brackets are just a Python list of column names.

## Quick Operations You'll Use Constantly

A couple of definitions for the terms used below:
- **Unique values**: the distinct values that appear in a column (duplicates removed).
- **Value counts**: a tally of how many times each unique value appears.

In [27]:
# Quick stats on a single column
print(f"Average GPA:    {df['gpa'].mean():.2f}")
print(f"Max age:        {df['age'].max()}")
print(f"Number unique cities: {df['city'].nunique()}")
print(f"Unique cities:  {df['city'].unique()}")

Average GPA:    3.39
Max age:        28
Number unique cities: 4
Unique cities:  ['Lahore' 'Karachi' 'Islamabad' 'Peshawar']

In [28]:
# value_counts() — how many of each unique value (extremely useful)
print("Students per city:")
print(df['city'].value_counts())

Students per city:
city
Lahore       4
Karachi      3
Islamabad    2
Peshawar     1
Name: count, dtype: int64

In [29]:
# Sorting
print("Sorted by GPA descending:")
print(df.sort_values('gpa', ascending=False).head())

Sorted by GPA descending:
   student_id    name  age      city  gpa
7           8  Maryam   24   Karachi  3.9
1           2    Sara   25   Karachi  3.8
5           6  Ayesha   23  Peshawar  3.7
3           4  Fatima   28    Lahore  3.6
0           1     Ali   22    Lahore  3.5

In [30]:
# Sorting by multiple columns
print("Sorted by city then age:")
print(df.sort_values(['city', 'age']))

Sorted by city then age:
   student_id    name  age       city  gpa
2           3   Ahmed   19  Islamabad  2.9
8           9   Usman   22  Islamabad  3.4
4           5  Hassan   21    Karachi  3.1
7           8  Maryam   24    Karachi  3.9
1           2    Sara   25    Karachi  3.8
6           7   Bilal   20     Lahore  2.8
0           1     Ali   22     Lahore  3.5
9          10    Zara   26     Lahore  3.2
3           4  Fatima   28     Lahore  3.6
5           6  Ayesha   23   Peshawar  3.7

## Practice Exercises

### Exercise 1
Create a Series of 6 monthly sales numbers (in any units) with month names as the index (Jan to Jun). Print the mean and find which month had the highest sales.

### Exercise 2
Create a DataFrame with 5 rows representing books, with columns: `title`, `author`, `year`, `pages`, `rating` (numeric 1 to 5). Print it and call `describe()` on it.

### Exercise 3
Using the `students.csv` from earlier, write code to:
- Print the shape and column names
- Find the student with the highest GPA
- Print how many students live in each city
- Print the average age of students with GPA above 3.5

### Exercise 4
Read the `students.csv` again, but this time:
- Use `student_id` as the index when reading
- Only load the columns `name`, `city`, and `gpa`

### Exercise 5 (challenge)
Create a DataFrame from this nested data:
```python
sales = [
    {'product': 'Laptop',  'price': 1200, 'units_sold': 30},
    {'product': 'Phone',   'price': 800,  'units_sold': 75},
    {'product': 'Tablet',  'price': 500,  'units_sold': 50},
    {'product': 'Monitor', 'price': 300,  'units_sold': 40},
]
```
- Add a new column `revenue` = price * units_sold
- Find the product with the highest revenue
- Print the total revenue across all products

In [31]:
# Exercise 1
sales = pd.Series(
    [120, 145, 132, 168, 155, 180],
    index=['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun']
)
print(sales)
print(f"\nMean: {sales.mean():.2f}")
print(f"Best month: {sales.idxmax()} (${sales.max()})")

Jan    120
Feb    145
Mar    132
Apr    168
May    155
Jun    180
dtype: int64

Mean: 150.00
Best month: Jun ($180)

In [32]:
# Exercise 2
books = pd.DataFrame({
    'title':  ['Atomic Habits', '1984', 'The Hobbit', 'Sapiens', 'Dune'],
    'author': ['James Clear', 'George Orwell', 'Tolkien', 'Harari', 'Herbert'],
    'year':   [2018, 1949, 1937, 2011, 1965],
    'pages':  [320, 328, 310, 443, 412],
    'rating': [4.5, 4.7, 4.6, 4.4, 4.3]
})
print(books)
print("\nDescribe:")
print(books.describe())

           title         author  year  pages  rating
0  Atomic Habits    James Clear  2018    320     4.5
1           1984  George Orwell  1949    328     4.7
2     The Hobbit        Tolkien  1937    310     4.6
3        Sapiens         Harari  2011    443     4.4
4           Dune        Herbert  1965    412     4.3

Describe:
             year       pages    rating
count     5.00000    5.000000  5.000000
mean   1976.00000  362.600000  4.500000
std      36.60601   60.587127  0.158114
min    1937.00000  310.000000  4.300000
25%    1949.00000  320.000000  4.400000
50%    1965.00000  328.000000  4.500000
75%    2011.00000  412.000000  4.600000
max    2018.00000  443.000000  4.700000

In [34]:
# Exercise 3
df = pd.read_csv('students.csv')

print(f"Shape: {df.shape}")
print(f"Columns: {df.columns.tolist()}")

top_idx = df['gpa'].idxmax()
print(f"\nHighest GPA student: {df.loc[top_idx, 'name']} ({df.loc[top_idx, 'gpa']})")

print("\nStudents per city:")
print(df['city'].value_counts())

avg_age_high = df[df['gpa'] > 3.5]['age'].mean()
print(f"\nAvg age (GPA > 3.5): {avg_age_high:.2f}")

Shape: (10, 5)
Columns: ['student_id', 'name', 'age', 'city', 'gpa']

Highest GPA student: Maryam (3.9)

Students per city:
city
Lahore       4
Karachi      3
Islamabad    2
Peshawar     1
Name: count, dtype: int64

Avg age (GPA > 3.5): 25.00

In [36]:
# Exercise 4
df = pd.read_csv(
    'students.csv',
    index_col='student_id',
    usecols=['student_id', 'name', 'city', 'gpa']
)
print(df)

              name       city  gpa
student_id
1              Ali     Lahore  3.5
2             Sara    Karachi  3.8
3            Ahmed  Islamabad  2.9
4           Fatima     Lahore  3.6
5           Hassan    Karachi  3.1
6           Ayesha   Peshawar  3.7
7            Bilal     Lahore  2.8
8           Maryam    Karachi  3.9
9            Usman  Islamabad  3.4
10            Zara     Lahore  3.2

In [37]:
# Exercise 5
sales_data = [
    {'product': 'Laptop',  'price': 1200, 'units_sold': 30},
    {'product': 'Phone',   'price': 800,  'units_sold': 75},
    {'product': 'Tablet',  'price': 500,  'units_sold': 50},
    {'product': 'Monitor', 'price': 300,  'units_sold': 40},
]

df = pd.DataFrame(sales_data)
df['revenue'] = df['price'] * df['units_sold']
print(df)

top_idx = df['revenue'].idxmax()
print(f"\nTop revenue product: {df.loc[top_idx, 'product']} (${df.loc[top_idx, 'revenue']:,})")
print(f"Total revenue: ${df['revenue'].sum():,}")

   product  price  units_sold  revenue
0   Laptop   1200          30    36000
1    Phone    800          75    60000
2   Tablet    500          50    25000
3  Monitor    300          40    12000

Top revenue product: Phone ($60,000)
Total revenue: $133,000